// The `Env` type (bindings + declared secrets) is generated by `wrangler types`
// into worker-configuration.d.ts from wrangler.jsonc — so it is intentionally
// NOT hand-written here. This file only declares the application-level shape of
// a queued transcription job (that's app data, not a binding).

export interface TranscribeJob {
  meetingId: string;
}

export type TranscribeBatch = MessageBatch<TranscribeJob>;
